[versions]
develocity = "4.3.1"
junit = "6.0.2"
jackson = "3.0.3"
mockitoExtension = "5.21.0"

[libraries]
develocity-plugin = { module = "com.gradle:develocity-gradle-plugin", version.ref = "develocity"}
jackson-bom = { module = "tools.jackson:jackson-bom", version.ref = "jackson" }
mockitoJunitJupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockitoExtension" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" } # keep for automatic updates

[plugins]
plugin-publish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
