name: Update jdks.yaml

on:
  workflow_dispatch:
  schedule: # Runs the action on the first day of every month at 3:42 UTC
    - cron: '42 3 1 * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-jdks:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Update jdks.yaml
        uses: gradle/update-jdks-action@main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          signoff: true
          sign-commits: true
          commit-message: "Update jdks.yaml"
          add-paths: .teamcity/jdks.yaml
          title: "Update jdks.yaml"
          body: "This PR updates JDK to the latest versions available in `.teamcity/jdks.yaml`."
          delete-branch: true
          branch-suffix: timestamp
          labels: "@dev-productivity"
